[build]
  functions = "netlify/functions"

[functions]
  included_files = ["src/data/productData.js"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"